on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true


jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # required to run python on ghub actions
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 

      - name: install black formatter
        run: pip install black

      - name: github script
        run: cat sample.json

      # passing in variables/secrets from the GHub secret store
      - name: replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["sample.json"]'
          tokenPrefix: '#('
          tokenSuffix: ')#'
        env:
          username_to_be_inserted: ${{ secrets.USERNAME }}
          password_to_be_inserted: ${{ secrets.PASSWORD }}
      
      # check for linting issues, using black formatter
      # see https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
      # for full docus on available args

      # this will not exit as we capture the exit code using `OR echo` and output a warning annotation
      - name: Lint Validation
        id: lint
        run: black --check --diff --color . || echo "::warning::Python code formatting issues detected"
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}


        # uses: psf/black@stable
        # with:
        #   options: "--check --diff --color"
        #   src: "./src/no_issues.py"
      
