on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true


jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Adding fetch-depth:0 is a good idea in order to fetch the all history (therefore all the branches)

      # required to run python on ghub actions
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 

      - run: for_merge_trigger='~1'
        if: ${{ github.event_name == 'push'}} 

      - name: install black formatter
        run: pip install black

      - name: Save modified files
        id: get_modified_files
        run: echo MODIFIED_FILES=$(./.github/scripts/modified_files.sh) >> $GITHUB_ENV
      
      - name: return modified python files
        run: echo $(./.github/scripts/modified_files.sh)

      - name: github script (before replace token)
        run: cat sample.json

      # passing in variables/secrets from the GHub secret store
      - name: replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["sample.json"]'
          tokenPrefix: '#('
          tokenSuffix: ')#'
        env:
          username_to_be_inserted: ${{ secrets.USERNAME }}
          password_to_be_inserted: ${{ secrets.PASSWORD }}
      
      - name: github script (after replace token)
        run: cat sample.json

      - name: List branches
        run: git branch -a

      - name: Lint modified Python files with Black
        run: |
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No Python files modified."
          else
            black --check --diff --color $MODIFIED_FILES || echo "::warning::Python code formatting issues detected"
          fi
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}

