name: My CICD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  determine_environments:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "save environments to run"
        id: environment_array
        run: |
          # for more information, please see script for comments
          bash my_array=$(./.github/scripts/determine_environment.sh) >> $GITHUB_OUTPUT
      - name: "return environments"
        run: echo ${{ steps.environment_array.outputs.my_array }}
    outputs:
      my_array: ${{ steps.environment_array.outputs.my_array }}

  deploy:
    needs: determine_environments
    uses: ./.github/workflows/full_workflow.yaml
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(needs.determine_environments.outputs.my_array) }} 
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}


