name: My CICD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    strategy:
      matrix:
        environment: ["dev", "prod"]
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["sample.json"]'
          tokenPrefix: '#('
          tokenSuffix: ')#'
        env:
          username_to_be_inserted: ${{ secrets.USERNAME }}
          password_to_be_inserted: ${{ secrets.PASSWORD }}

      - name: github script
        run: cat sample.json
      