name: My CICD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/full_workflow.yaml
    strategy:
      max-parallel: 1
      matrix:
        environment: [dev, prod]
    with:
      environment: ${{ matrix.environment }}


